version: '3.8'

services:
  app:
    container_name: parkinglot
    image: fahmimahmud/parking-lot-management
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - parkinglot-network

  db:
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parkinglot
    networks:
      - parkinglot-network

networks:
  parkinglot-network:
    driver: bridge
